### ISSUE TITLE
Streamline release process

### ISSUE THREAD

**Issue by johanneskoester** [snakemake/snakedeploy#14]
When creating a new release, I first need to manually update the version in version.py. Can we automate that from the tag somehow? Snakemake uses versioneer for that, but maybe there are more modern solutions nowadays. I just don't want to mess with your setup.py, so maybe you can have a look @vsoch?

**Comment by vsoch** [comment]
@johanneskoester versioneer is a fine solution - the other one I’ve heard about (but less so) is bumpversion but it looks like the original isn’t maintained and a second fork is suggested https://github.com/c4urself/bump2version

I’d be ok if you want to use versioneer and be consistent with Snakemake!

**Comment by vsoch** [comment]
Let me know if you want me to mimic the setup in snakemake with versioneer here, happy to give that a shot.

**Comment by johanneskoester** [comment]
Yeah, versioneer would be fine, thanks!
