### ISSUE TITLE
`--use-singularity` broken?

### ISSUE THREAD

**Issue by nikostr** [snakemake/snakedeploy#16]
* snakedeploy version: 0.1.3
* Python version: 3.9.5
* Operating System: Ubuntu 20.04

### Description
Workflows downloaded using snakedeploy do not play nice with rules requiring singularity containers. The singularity containers do not get downloaded, and rules relying on the containers are not executed within the container. Since the workflow works when cloning, the issue is likely with snakedeploy.

As an aside, I notice that the messages regarding the cache directive also disappear when using snakedeploy.

### What I Did

```
mamba create -c bioconda -c conda-forge --name snakemake snakemake snakedeploy
conda activate snakemake
git clone https://github.com/nikostr/dna-seq-deepvariant-glnexus-variant-calling.git
mkdir snakedeploy_test
cd snakedeploy_test
snakedeploy deploy-workflow https://github.com/nikostr/dna-seq-deepvariant-glnexus-variant-calling . --tag v0.3.0
cp -r ../dna-seq-deepvariant-glnexus-variant-calling/.tests .
```

Running `snakemake -j1 --use-conda --conda-frontend mamba --use-singularity` works in the cloned but not in the deployed directory.

**Comment by johanneskoester** [comment]
Thanks for reporting! This was a bug in Snakemake, but it will be fixed by merging the PR referred above.
